#!/bin/bash

echo "Greater"
./program <programGreater.imp >programGreater.mp
./interpreter programGreater.mp

echo "GreaterEqual"
./program <programGreaterEqual.imp >programGreaterEqual.mp
./interpreter programGreaterEqual.mp

echo "Lesser"
./program <programLesser.imp >programLesser.mp
./interpreter programLesser.mp

echo "LesserEqual"
./program <programLesserEqual.imp >programLesserEqual.mp
./interpreter programLesserEqual.mp

echo "Equal"
./program <programRowne.imp >programRowne.mp
./interpreter programRowne.mp

echo "NotEqual"
./program <programRozne.imp >programRozne.mp
./interpreter programRozne.mp
